### ISSUE TITLE
phone adaption

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/rcpp_wp#1]
Switch to one-column layout on smaller screens. Texts and events interlaced chronologically.

**Comment by manegame** [comment]
One column layout in place. Working on problem with articles that get 'clipped' where they should not be. 
![Uploading Schermafbeelding 2016-09-13 om 12.28.35.png…]()
![schermafbeelding 2016-09-13 om 12 28 43](https://cloud.githubusercontent.com/assets/17074938/18470620/a7618f3a-79ad-11e6-908a-8a626f1ace9c.png)
